INSERT INTO USER (USER_ID, USER_NAME, PASSWORD) VALUES (1, 'rafael', '$2a$10$/gYyB6Xso6cR4cGFXTef7OgTzObE0K0z/Z4sSQxgWEt/chMdrl4Cq');
INSERT INTO USER (USER_ID, USER_NAME, PASSWORD) VALUES (2, 'pedro', '$2a$10$/gYyB6Xso6cR4cGFXTef7OgTzObE0K0z/Z4sSQxgWEt/chMdrl4Cq'); //568

INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (1, 'rafael', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (2, 'rafael', 'USER');
INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (3, 'pedro', 'USER');