INSERT INTO USER (USER_ID, USER_NAME, PASSWORD) VALUES (1, 'rafael', 'password');
INSERT INTO USER (USER_ID, USER_NAME, PASSWORD) VALUES (2, 'pedro', '561');

INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (1, 'rafael', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (2, 'rafael', 'USER');
INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (3, 'pedro', 'USER');